require('dotenv').config();
const express = require('express');
const { Octokit } = require('@octokit/rest');

const app = express();
app.use(express.json());

// ============================================
// CONFIGURATION - Load from .env file
// ============================================

// ClickUp Configuration
const CLICKUP_API_KEY = process.env.CLICKUP_API_KEY;
const CLICKUP_SECRET = process.env.CLICKUP_SECRET; // TODO: Implement webhook secret validation
const CLICKUP_BOT_USER_ID = process.env.CLICKUP_BOT_USER_ID;

// GitHub Configuration
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_OWNER = process.env.GITHUB_OWNER;
const GITHUB_REPO = process.env.GITHUB_REPO;
const GITHUB_BASE_BRANCH = process.env.GITHUB_BASE_BRANCH || 'main';

// Initialize Octokit
const octokit = new Octokit({
  auth: GITHUB_TOKEN
});

// ============================================
// WEBHOOK ENDPOINT
// ============================================

app.post('/webhook', async (req, res) => {
  try {
    console.log('Received ClickUp webhook event');

    // TODO: Validate webhook signature
    // const signature = req.headers['x-signature'];
    // if (!validateWebhookSignature(signature, req.body, CLICKUP_WEBHOOK_SECRET)) {
    //   return res.status(401).json({ error: 'Invalid signature' });
    // }

    const event = req.body;

    // Log the task payload
    console.log('Task Title:', event.task_id);
    console.log('Event Type:', event.event);

    // Check if this is a task assignment event for our bot
    if (event.event === 'taskAssigneeUpdated' || event.event === 'taskCreated') {
      const task = event.task_id ? await getTaskDetails(event.task_id) : null;

      if (task) {
        console.log('Task Title:', task.name);
        console.log('Task Description:', task.description || '(no description)');

        // Check if the task is assigned to our bot user
        const assignees = task.assignees || [];
        const isBotAssigned = assignees.some(assignee => assignee.id === CLICKUP_BOT_USER_ID);

        if (isBotAssigned) {
          console.log('Task assigned to bot - processing...');

          // Process the task
          await processTask(task);

          return res.status(200).json({
            success: true,
            message: 'Task processed and PR created'
          });
        }
      }
    }

    // Acknowledge webhook for other events
    res.status(200).json({ success: true, message: 'Webhook received' });

  } catch (error) {
    console.error('Error processing webhook:', error);
    res.status(500).json({ error: error.message });
  }
});

// ============================================
// HELPER FUNCTIONS
// ============================================

// Get task details from ClickUp API
async function getTaskDetails(taskId) {
  const axios = require('axios');

  try {
    const response = await axios.get(`https://api.clickup.com/api/v2/task/${taskId}`, {
      headers: {
        'Authorization': CLICKUP_API_KEY,
        'Content-Type': 'application/json'
      }
    });

    return response.data;
  } catch (error) {
    console.error('Error fetching task details:', error.message);
    return null;
  }
}

// Main task processing function
async function processTask(task) {
  const taskId = task.id;
  const taskTitle = task.name;
  const taskDescription = task.description || '';

  console.log(`Processing task ${taskId}: ${taskTitle}`);

  // ============================================
  // CLAUDE API CALL - Currently Mocked
  // ============================================
  // TODO: Replace this mock with actual Claude API call
  // const generatedCode = await callClaudeAPI(taskTitle, taskDescription);

  // For now, return a hardcoded "Hello World" JavaScript file
  const generatedCode = `// Generated from ClickUp Task: ${taskTitle}
// Task ID: ${taskId}
// Description: ${taskDescription}

console.log("Hello World");

// This is a mocked file.
// TODO: Integrate Claude API to generate actual code based on the task.
`;

  // ============================================
  // GITHUB OPERATIONS
  // ============================================

  const branchName = `task-${taskId}`;
  const fileName = 'generated-code.js';
  const commitMessage = `Add generated code for ClickUp task: ${taskTitle}`;
  const prTitle = `[ClickUp #${taskId}] ${taskTitle}`;
  const prBody = `## ClickUp Task

**Task ID:** ${taskId}
**Title:** ${taskTitle}
**Description:**
${taskDescription || 'No description provided'}

---

This PR was automatically generated by the ClickUp-Claude-GitHub integration.

Generated file: \`${fileName}\`
`;

  try {
    // 1. Get the reference of the base branch
    const { data: refData } = await octokit.git.getRef({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      ref: `heads/${GITHUB_BASE_BRANCH}`
    });

    const baseSha = refData.object.sha;
    console.log(`Base branch SHA: ${baseSha}`);

    // 2. Create a new branch
    await octokit.git.createRef({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      ref: `refs/heads/${branchName}`,
      sha: baseSha
    });

    console.log(`Created branch: ${branchName}`);

    // 3. Create/update the file in the new branch
    const contentEncoded = Buffer.from(generatedCode).toString('base64');

    await octokit.repos.createOrUpdateFileContents({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      path: fileName,
      message: commitMessage,
      content: contentEncoded,
      branch: branchName
    });

    console.log(`Committed file: ${fileName}`);

    // 4. Create a Pull Request
    const { data: prData } = await octokit.pulls.create({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      title: prTitle,
      head: branchName,
      base: GITHUB_BASE_BRANCH,
      body: prBody
    });

    console.log(`Pull Request created: ${prData.html_url}`);

    return prData;

  } catch (error) {
    console.error('Error creating GitHub PR:', error.message);
    throw error;
  }
}

// ============================================
// FUTURE: Claude API Integration
// ============================================
// async function callClaudeAPI(taskTitle, taskDescription) {
//   const axios = require('axios');
//
//   const response = await axios.post('https://api.anthropic.com/v1/messages', {
//     model: 'claude-3-5-sonnet-20241022',
//     max_tokens: 4096,
//     messages: [{
//       role: 'user',
//       content: `Generate JavaScript code for the following task:\n\nTitle: ${taskTitle}\n\nDescription: ${taskDescription}`
//     }]
//   }, {
//     headers: {
//       'x-api-key': 'your-claude-api-key',
//       'anthropic-version': '2023-06-01',
//       'content-type': 'application/json'
//     }
//   });
//
//   return response.data.content[0].text;
// }

// ============================================
// SERVER
// ============================================

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(`ClickUp-Claude-GitHub integration server running on port ${PORT}`);
  console.log(`Webhook endpoint: http://localhost:${PORT}/webhook`);
});
